### ISSUE TITLE
How to push next modal sheet without prior (enclosing) one? [GoRouter]

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/smooth_sheets#109]
### Discussed in https://github.com/fujidaiti/smooth_sheets/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **bqubique** May  4, 2024</sup>

Based on [this code](https://github.com/fujidaiti/smooth_sheets/discussions/85#discussioncomment-8996658) block, if I want to directly go to Genre sheet, how would I go for it using GoRouter? 
Normally I would expect this to work:
```
context.go('/intro/genre');
```
But I'm getting this error:
```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
The sheet extent and the dimensions values must be finalized during the layout phase.
'package:smooth_sheets/src/foundation/framework.dart':
Failed assertion: line 125 pos 7: '_extent.hasPixels'

The relevant error-causing widget was:
    NavigationSheet NavigationSheet:file:///Users/blinqipa/Desktop/wolt_test/lib/main.dart:181:16
```

What would be the correct way to handle this?</div>

**Comment by bqubique** [comment]
Thanks for the quick fix on this @fujidaiti. Just tested it and it works perfectly!
