### ISSUE TITLE
NavigationSheetRoute is no longer exported in 0.5.0

### ISSUE THREAD

**Issue by naamapps** [fujidaiti/smooth_sheets#110]
Please release a quick update that also exports NavigationSheetRoute.
I am using it to check whether the current modalRoute is a navigation sheet or not, so 0.5.0 is breaking for me.
In previous version this class was exported and could be used externally from the package.

```dart
final route = ModalRoute.of(context);
final isNavigationSheet = route is NavigationSheetRoute;
```

**Comment by fujidaiti** [comment]
`NavigationSheetRoute` was moved to a separate file in 0.5.0 and I forgot to export it. Thanks for reporting this!

**Comment by naamapps** [comment]
@fujidaiti King 👑
