### ISSUE TITLE
Add a way to handle dismissing modal sheet events in one place

### ISSUE THREAD

**Issue by vincevargadev** [fujidaiti/smooth_sheets#130]
In the `todo_list` example app, the sheet should not be dismissible when the form was changed.

When the user tries to swipe down, the `SheetDismissible`'s `onDismiss` callback is correctly triggered and depending on its return value, it doesn't allow closing the sheet by swiping down, and first asks for confirmation.

However, the user can still tap outside of the sheet, and when the barrier is tapped, the sheet closes regardless of whether the form was changed or not.

See demo in video:

https://github.com/fujidaiti/smooth_sheets/assets/9061239/3d961dc9-a78f-405f-bc66-342d72d31e30

I am not sure if you want to consider it a bug or feature request (in the end it doesn't matter), in my opinion making something like this easy should be part of this package.

Thank you for your work on the package, it's really the best out there!

```
flutter run --target lib/showcase/todo_list/main.dart
```

**Comment by fujidaiti** [comment]
Your suggestion makes sense, but is setting `barrierDismissible` to false not enough?

```dart
Future<Todo?> showTodoEditor(BuildContext context) {
  return Navigator.push(
    context,
    ModalSheetRoute(
      barrierDismissible: false,
      builder: (context) => const TodoEditor(),
    ),
  );
}
```

>In the todo_list example app, the sheet should not be dismissible when the form was changed.

This is true. I will update the todo list example.

>// This is unfortunately not exposed by smooth_sheets...
// ignore: implementation_imports
import 'package:smooth_sheets/src/foundation/sheet_status.dart';

Oops, I didn't notice that. It should be exported.

**Comment by fujidaiti** [comment]
I certainly agree that there needs to be a common way to handle the on-dismiss events that occur when tapping the barrier or dragging down the sheet (it could be something like [PopScope](https://api.flutter.dev/flutter/widgets/PopScope-class.html)).
