### ISSUE TITLE
Unable to build version `0.6.0` for Flutter versions `< 3.22.0`

### ISSUE THREAD

**Issue by JvSomeren** [fujidaiti/smooth_sheets#144]
While building version `0.6.0` of `smooth_sheets` an error is thrown for Flutter versions lower than `3.22.0`.

The throw error is as follows:
`.pub-cache/hosted/pub.dev/smooth_sheets-0.6.0/lib/src/foundation/sheet_drag.dart:300:34: Error: The getter 'localPosition' isn't defined for the class 'DragEndDetails'.`

It boils down to [this change](https://github.com/flutter/flutter/commit/fa71e8029b1b70b774f6ac538dbcea89c57a2f62) to Flutter itself which is only available since Flutter `3.22.0`.

This error does not occur for `smooth_sheets` version `0.5.3` while building with Flutter version `3.19.3`. Due to package constraints we are currently not yet able to upgrade to the latest Flutter version.

**Comment by fujidaiti** [comment]
Hi @JvSomeren,

Thank you for reporting this. The patch will be included in v0.7.0.
