### ISSUE TITLE
Add option to StretchingSheetPhysics to limit stretchable direction

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/smooth_sheets#159]
Hi @habibasseiss, 

> When the screen gets pulled up, I don't think it's a matter of giving the background a color, instead the physics could "attach" to the bottom to prevent showing the parent screen.

Thanks for the suggestion! I agree with this idea and so I will add an option to `StretchingSheetPhysics` to limit the directions in which the sheet can stretch.

```dart
// Does not work in the current version
DraggableSheet(
  physics: StretchingSheetPhysics(
  // This disables the stretching effect when overdragging upward
    direction: StretchingBehaviorDIrection.downward,
  ),
);
```

_Originally posted by @fujidaiti in https://github.com/fujidaiti/smooth_sheets/discussions/157#discussioncomment-9668806_

**Comment by appinteractive** [comment]
Is there also a way to specify the max stretch distance?

**Comment by mark8044** [comment]
Would it be a hard stop when pulling up, or still give a Bouncing effect?

**Comment by habibasseiss** [comment]
I'd love to have max stretch like @appinteractive suggested. In the native sheet, the stretch stops at the reduced parent page limits.

Here's the behavior of a basic sheet in SwiftUI:

https://github.com/fujidaiti/smooth_sheets/assets/521863/c189bc02-c0d0-4956-bc7f-31bbbd063442
Source code: https://gist.github.com/habibasseiss/d14c375c40b6a543a8043d2aedc00c36

Having that in addition to the sheet attaching the bottom would be amazing!

**Comment by fujidaiti** [comment]
@appinteractive 

>Is there also a way to specify the max stretch distance?

[StretchingSheetPhysics.stretchingRange](https://pub.dev/documentation/smooth_sheets/latest/smooth_sheets/StretchingSheetPhysics/StretchingSheetPhysics.html) could be used for this purpose. It determines how many pixels the sheet can be overdragged.

```dart
// The sheet never be overdragged.
StretchingSheetPhysics(stretchingRange: const Extent.pixels(0));

// The sheet can be overdragged by ±100 pixels.
StretchingSheetPhysics(stretchingRange: const Extent.pixels(100));

// The sheet can be overdragged by ±10% of the sheet height.
StretchingSheetPhysics(stretchingRange: const Extent.proportional(0.1));
```

**Comment by appinteractive** [comment]
> I think it would be nice to allow this property to be set for each direction.

That's a great idea!
