### ISSUE TITLE
Make SheetContentScaffold.bottomBar more customizable

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/smooth_sheets#19]
Currently, [SheetContentScaffold.requiredMinExtentForStickyBottomBar](https://pub.dev/documentation/smooth_sheets/latest/smooth_sheets/SheetContentScaffold/requiredMinExtentForStickyBottomBar.html) is the only way to customize the behavior of the bottom bar, but it is inflexible and not intuitive.

Here's the list of topics this new feature should cover:
- Hiding the bottom bar when the on-screen keyboard appears
- Sticky bottom bar
- Non-sticky bottom bar

**Comment by appinteractive** [comment]
I have a use case for a chat sheet (multiple snap points) with
- 1. a sticky input
- 2. that needs to avoid the keyboard
- 3. needs to still be visible when the sheet is in its minimal position. 

Maybe that helps in evaluation. 

And just a huge thanks for that lib, it's by far the most promising thing I see for the most possible use cases. Big thanks for that. 💥👍
