### ISSUE TITLE
How to make the height adaptive to the content instead of specifying the Extent

### ISSUE THREAD

**Issue by itMcdull** [fujidaiti/smooth_sheets#203]
How to make the height adaptive to the content instead of specifying the Extent

**Comment by fujidaiti** [comment]
Hi @itMcdull,

You can use [Extent.proportional](https://pub.dev/documentation/smooth_sheets/latest/smooth_sheets/Extent/Extent.proportional.html):

```dart
DraggableSheet(
    // Set the minimum and initial extent (the visible height of the sheet) to 50% of the content height.
    minExtent: const Extent.proportional(0.5),
    initialExtent: const Extent.proportional(0.5),
    ...,
);
```

**Comment by codeOfJannik** [comment]
@fujidaiti What needs to be done to have a dynamically growing sheet? E.g. the sheet contains a Column with a Stateful widget as first element, let's say a Text box which may have either 2 or 3 lines. The second element of the column is a button.
Initially the sheet is rendered with 2 lines of text with maxExtent and initialExtent of `Èxtent.proportional(1)`, so the button is perfectly aligned with the bottom of the screen.
After a few seconds the text box widget updates the state and has now 3 lines of text. But that leads to the situation that all content below the text box is pushed down, so the button is clipped by the bottom screen edge (absolut extent stays the same but proportional extent is now something like 0.9...)
I would rather have the sheet growing upwards, keeping the button completely visible, means the proportional extent should stay at 1 (absolute extent would increase by the height of the text line height).
Here's a minimal example of the situation:

```dart
DraggableSheet(
  controller: sheetController,
  minExtent: Extent.pixels(100.0),
  child: SheetContentScaffold(
    appBar: SomeHeaderWidget(),
    body: Padding(
      padding: EdgeInsets.symmetric(horizontal: 24),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          SizedBox(height: 12),
          SomeStatefulTextBox(),
          SizedBox(height: 12),
          SomeActionButton(),
        ],
      ),
    ),
  ),
);
```

**Comment by fujidaiti** [comment]
Hi @codeOfJannik,

Thank you for reporting the bug. I've transferred it to issue #226, as it is not related to this issue.
Please follow #226 for any upcoming updates.
