### ISSUE TITLE
Sometimes touch is ignored when scrollable sheet reaches edge

### ISSUE THREAD

**Issue by naamapps** [fujidaiti/smooth_sheets#207]
This issue occurs not only for bottom edge, but also for top edge, but it's harder to reproduce. 

Version: smooth_sheets: ^0.9.0
See video:

https://github.com/user-attachments/assets/e76a7401-f32d-4deb-bee0-6ce476516b7d

**Comment by fujidaiti** [comment]
Hi @naamapps,

Does it happen with v0.8.2 or earlier?

**Comment by fujidaiti** [comment]
I could reproduce the same behavior in the AI playlist generator example at this commit (b0b2e871a1ab805c8391aea6f94f00e93a191f32).
