### ISSUE TITLE
Touch is ignored issue not fixed for top edge

### ISSUE THREAD

**Issue by naamapps** [fujidaiti/smooth_sheets#212]
Hi,
After issue #207 got resolved, I managed to replicate the same for the top edge.
It's pretty hard to reproduce, but as you can see in the video, the issue still persists.

https://github.com/user-attachments/assets/a609ffc3-c441-46f6-a98b-8493f693c719

**Comment by fujidaiti** [comment]
Hi @naamapps,

How frequently do you encounter this issue?

**Comment by naamapps** [comment]
Hi @fujidaiti,
Unfortunately, quite frequently.

**Comment by fujidaiti** [comment]
@naamapps 

I've pushed a fix for this issue to the [touch-ignored](https://github.com/fujidaiti/smooth_sheets/tree/touch-ignored) branch. 
Could you test it with your app? I was only able to reproduce the issue in the tests.

**Comment by naamapps** [comment]
@fujidaiti sorry for the delay, my macbook got busted a few days ago, sent it for repair.
Once they return it, I'll be able to test your solution.

**Comment by naamapps** [comment]
Hi @fujidaiti, just tested it, and i can't reproduce anymore. i think you fixed the issue.
