### ISSUE TITLE
ScrollableSheet with PageView and two pages don't stop momentum when holding the scrollable

### ISSUE THREAD

**Issue by naamapps** [fujidaiti/smooth_sheets#214]
Hi,
Found a bug where if you have a PageView inside a ScrollableSheet, and the PageView have more than 1 page, while scrolling the list inside any of the pages, and then trying to stop the scroll by holding the list, it will not stop, but will continue with the momentum.
Probably related to #196 - need to take PageView into consideration too.

**Comment by naamapps** [comment]
See video:

https://github.com/user-attachments/assets/072b978c-bef1-4db3-9a87-0c3db419a8b2

**Comment by NinoBass** [comment]
Same thing happening with a CustomScrollView
