### ISSUE TITLE
Weird behavior when opening keyboard and changing content height simultaneously 

### ISSUE THREAD

**Issue by naamapps** [fujidaiti/smooth_sheets#263]
Hi,
I encountered a bug where opening the keyboard and changing content height simultaneously gives a very weird looking behavior to the user.
When opening the keyboard and the content shrinks - the sheet takes its sweet time to settle.
When closing the keyboard and the content grows - the sheet jumps up and looks very jittery to the eye.
At the end of the video - the sheet went down for some reason when I closed the keyboard (i didn't do anything special to make this happen).

I don't have a reproducible code just yet. let me know if you need one and I'll find the time to build it.

See video:
https://github.com/user-attachments/assets/64bb0f7e-e381-417d-b880-cefaa85638f1

**Comment by fujidaiti** [comment]
Hi @naamapps,

What kind of sheet does your app use, and does it use `SheetContentScaffold`?

> I don't have a reproducible code just yet. let me know if you need one and I'll find the time to build it.

Yes, that would be very helpful.

**Comment by naamapps** [comment]
> What kind of sheet does your app use, and does it use `SheetContentScaffold`?

It's a ScrollableSheet, and it does not use SheetContentScaffold. I'll try it though.

+I'll try to create a reproducible code ASAP.

**Comment by naamapps** [comment]
Hi @fujidaiti, with SheetContentScaffold it didn't work too.
But I now understand the root issue, and (I think) it's not the package fault.
The problem is that the sheet reacted to the keyboard opening and closing, which is fine in itself, but only I needed that keyboard reactivity when tapping the search emoji button.
So basically what happened was that the main emoji gridview got pushed up (when it wasn't needed to) and then the view switched to the search emoji view, this caused the weird behavior.
When tapping the search button I switch the whole widget - meaning I have 2 kinds of sheets here - ScrollableSheet & DraggableSheet, My solution was to wrap the ScrollableSheet with MediaQuery.removeViewInsets like so:
```dart
MediaQuery.removeViewInsets(
      context: context,
      removeBottom: true,
      child: ScrollableSheet(
             .....
       )
)
```

This made the emoji gridview non-reactive to the keyboard which results in a much better and smoother transition:

https://github.com/user-attachments/assets/e097f82e-e825-481d-8c3e-e52c33586c46

**Comment by fujidaiti** [comment]
> This made the emoji gridview non-reactive to the keyboard which results in a much better and smoother transition:

Currently, I’ve been working on supporting margins around a sheet (#76). Once it is merged, I recommend using NavigationSheet for sheets with nested navigation instead of ScrollableSheet.

**Comment by naamapps** [comment]
Thanks @fujidaiti, 
I'm not sure what's the connection with the keyboard issue and the margins around the sheet, but I will make sure to check this out once it's available.
FYI, there isn't any navigation in this use case actually, I'm literally just switching widgets inside the build function conditionally.

**Comment by fujidaiti** [comment]
> I'm literally just switching widgets inside the build function conditionally.

Yeah, that's fine. But if you use navigation to switch from the emoji list to the search screen, it gives you a smoother transition, where the sheet height gradually changes from, say, 200px (for the emoji list) to 80px (for the search bar).

**Comment by naamapps** [comment]
Are you sure it absorbs the keyboard height when using NavigationSheet? I could of sworn I tried it before and it behaved partially the same where the emoji list jumps up because the keyboard pops up.
But I'm really not sure, will test this once the margins feature releases.

**Comment by fujidaiti** [comment]
> Are you sure it absorbs the keyboard height when using NavigationSheet? 

Sorry for the confusion. Use NavigationSheet for a smoother transition, and use SheetContentScaffold for absorbing the keyboard height. An example of this use case can be seen [here](https://github.com/fujidaiti/smooth_sheets/blob/main/example/lib/tutorial/navigation_sheet_and_keyboard.dart).
