### ISSUE TITLE
SheetContentScaffold overlaps content and does not expand

### ISSUE THREAD

**Issue by Clon1998** [fujidaiti/smooth_sheets#267]
When using `SheetContentScaffold` with just a `ListView` or any other scrollable as the body, the sheet will not expand to the full extent. Additionally, it is impossible to scroll to the last few items in the listview.

When using the `SheetContentScaffold` with a bottom bar, the bottom bar will always float on top of the body, and the last few items can't be reached as they are underneath the bottom bar.

Version:  smooth_sheets: ^1.0.0-f324.0.10.1

Here is a minimal example code alongside a screen recording of the issue:
```dart
    var listView = ListView.builder(
      shrinkWrap: true,
      itemBuilder: (context, index) {
        return ListTile(
          title: Text('Item $index'),
        );
      },
      itemCount: 5,
    );
    final content = SheetContentScaffold(
        body: listView);
    // final content = listView;

    final withBg = SafeArea(
      // bottom: false,
      // top: false,
      child: Material(
        borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
        clipBehavior: Clip.antiAlias,
        child: content,
      ),
    );

    return ScrollableSheet(child: withBg);
```

Recording of the usage of the `SheetContentScaffold`, last item is unreachable and not fully expanded:

https://github.com/user-attachments/assets/fdf5d936-ea01-4064-acd0-e9389e1fa331

Recording without using the `SheetContentScaffold,` all items are accessible, and the sheet is fully expanded:

https://github.com/user-attachments/assets/301f2ee8-5dee-463a-9e46-a4589c3ef007

**Comment by fujidaiti** [comment]
@Clon1998 Try removing shrinkWrap:true in the listview.

**Comment by GHkmmm** [comment]
I encountered the same problem as you, but I only need these few lines of code to reproduce it!

```dart
class DemoWidget extends StatelessWidget {
  const DemoWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return ScrollableSheet(
      minPosition: SheetAnchor.proportional(0),
      maxPosition: SheetAnchor.proportional(0.9),
      initialPosition: SheetAnchor.proportional(0.9),
      child: ListView.builder(
        itemCount: 50,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('Item $index'),
          );
        },
      ),
    );
  }
}

```

**Comment by Clon1998** [comment]
> I encountered the same problem as you, but I only need these few lines of code to reproduce it!
> 
> 
> 
> ```dart
> 
> class DemoWidget extends StatelessWidget {
> 
>   const DemoWidget({super.key});
> 
> 
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return ScrollableSheet(
> 
>       minPosition: SheetAnchor.proportional(0),
> 
>       maxPosition: SheetAnchor.proportional(0.9),
> 
>       initialPosition: SheetAnchor.proportional(0.9),
> 
>       child: ListView.builder(
> 
>         itemCount: 50,
> 
>         itemBuilder: (context, index) {
> 
>           return ListTile(
> 
>             title: Text('Item $index'),
> 
>           );
> 
>         },
> 
>       ),
> 
>     );
> 
>   }
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> When I set "maxPosition" and "initialPosition" to "SheetAnchor.proportional(1)" it's ok but it's not the height I expected.
> 
> 
> 
> Version Info:
> 
> 
> 
> ```bash
> 
> smooth_sheets: ^1.0.0-f324.0.9.4
> 
> 
> 
> Flutter 3.24.3 • channel stable •
> 
> https://github.com/flutter/flutter.git
> 
> Framework • revision 2663184aa7 (5 周前) • 2024-09-11
> 
> 16:27:48 -0500
> 
> Engine • revision 36335019a8
> 
> Tools • Dart 3.5.3 • DevTools 2.37.3
> 
> ```
> 
> 
> 
> 

I actually creates a different issue for that:

https://github.com/fujidaiti/smooth_sheets/issues/265

**Comment by fujidaiti** [comment]
@Clon1998 

> ```dart
>     final withBg = SafeArea(
>       // bottom: false,
>       // top: false,
>       child: Material(
>         borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
>         clipBehavior: Clip.antiAlias,
>         child: content,
>       ),
>     );
> 
>     return ScrollableSheet(child: withBg);
> ```

I suspect that the Material inside the SafeArea is causing the issue. I recommend wrapping the ScrollableSheet with the SafeArea instead.

```dart
return SafeArea(child: ScrollableSheet(...));
```

**Comment by Clon1998** [comment]
> @Clon1998
> 
> > ```dart
> >     final withBg = SafeArea(
> >       // bottom: false,
> >       // top: false,
> >       child: Material(
> >         borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
> >         clipBehavior: Clip.antiAlias,
> >         child: content,
> >       ),
> >     );
> > 
> >     return ScrollableSheet(child: withBg);
> > ```
> 
> I suspect that the Material inside the SafeArea is causing the issue. I recommend moving the SafeArea outside of the ScrollableSheet instead.
> 
> ```dart
> return SafeArea(child: ScrollableSheet(...));
> ```

This seems to solve the issue. Will test the API further but for now it solves it
