### ISSUE TITLE
When keyboard is shown, all content is getting pushed up.

### ISSUE THREAD

**Issue by haroke4** [fujidaiti/smooth_sheets#275]
Hello!

Thank you for providing such an amazing package. I’ve encountered an issue related to keyboard behavior that I'd like to report for improvement.

Issue Description:
When interacting with a TextField in my app, I’ve noticed that the appearance of the keyboard pushes all of the screen content upward. This behavior is quite disruptive, as it affects the overall layout and user experience, especially when there are multiple UI components involved.

Expected Behavior:
I would prefer the keyboard to appear overlayed on top of the content without shifting the entire view upward. However, if the TextField is located behind the keyboard, it should push only that section of content up to maintain visibility and usability.

My code:
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pilligrim/core/widgets/base/screen_base.dart';
import 'package:pilligrim/core/widgets/button/my_button.dart';
import 'package:smooth_sheets/smooth_sheets.dart';

class TestMainScreen extends StatelessWidget {
  const TestMainScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return ScreenBase.titled(
      title: 'Test',
      hasBottomSheet: true,
      child: Column(
        children: [
          MyButton.primary(
            onPressed: () {
              _onButtonPressed();
            },
            text: "123",
          ),
        ],
      ),
    );
  }

  void _onButtonPressed() {
    Navigator.push(
      Get.context!,
      CupertinoModalSheetRoute(
        swipeDismissible: true,
        builder: (context) {
          return SafeArea(
            bottom: false,
            child: ScrollableSheet(
              physics: BouncingSheetPhysics(parent: SnappingSheetPhysics()),
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(16),
                ),
                clipBehavior: Clip.antiAlias,
                child: SheetContentScaffold(

                  body: ListView(
                    shrinkWrap: true,
                    children: [
                      TextField(),
                      for (int i = 0; i < 4; i++) testCard(i),
                    ],
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget testCard(int index) {
    return Container(
      color: index.isEven ? Colors.red : Colors.blue,
      height: 100,
    );
  }
}

```

Video:

https://github.com/user-attachments/assets/5b5a3ecb-0a80-40d0-af0c-304f975e0932

**Comment by fujidaiti** [comment]
Hi @haroke4,

> I would prefer the keyboard to appear overlayed on top of the content without shifting the entire view upward.

In this case, you need to specify multiple snap positions (by default, the sheet only snaps to a position where the entire content is visible). See [this tutorial](https://github.com/fujidaiti/smooth_sheets/blob/main/example/lib/tutorial/textfield_with_multiple_stops.dart) for reference.

**Comment by haroke4** [comment]
Solved my issue ;3

**Comment by haroke4** [comment]
Thanksss!!

**Comment by KiddoV** [comment]
This is not a good solution, what if I don't want to use `snaps` for my sheet?
This package inspired by `WoltModalSheet`, which doesn't have this issue.

**Comment by fujidaiti** [comment]
@KiddoV 

> This is not a good solution, what if I don't want to use snaps for my sheet?

`SteplessSnapGrid` would be a solution for this case. See [this example](https://github.com/fujidaiti/smooth_sheets/blob/main/example/lib/tutorial/physics_and_snap_grid.dart) for more details.

**Comment by fujidaiti** [comment]
@KiddoV 

That's my bad. It seems something went wrong with SteplessSnapGrid. Thank you for reporting it.

https://github.com/user-attachments/assets/d127f5a3-7577-4ad5-879e-fbe28921d226

> the sheet still push up. Only if user change to different offset, then the sheet stay. 

I'm still not sure what the expected behavior is. If you want to completely ignore the keyboard appearance and  prevent the sheet from pushing up, try setting [shrinkChildToAvoidDynamicOverlap](https://pub.dev/documentation/smooth_sheets/latest/smooth_sheets/Sheet/shrinkChildToAvoidDynamicOverlap.html) to `false` in the Sheet's constructor:

```dart
Sheet(
  shrinkChildToAvoidDynamicOverlap: false, // True by default
);
```

**Comment by KiddoV** [comment]
@fujidaiti Well, I just want a normal behavior like what `WoltSheet` does, when user tap on text field => sheet stay (don't push up), when sheet has sticky bottom bar, the bottom bar get push up with keyboard, but of course sheet still stay.

**Comment by KiddoV** [comment]
@fujidaiti is there a way to make the top bar of the sheet become a full-screen title bar, while respecting the safe area, when the sheet is fully expanded? 
This way, I don't have to deal with fixing the sheet pushing up manually—just let it expand into a full-screen page, and return to normal when it collapses.

**Comment by fujidaiti** [comment]
@KiddoV I created a feature request for this use case. Please follow and comment on #408 if you have any questions, thanks.
